spring.application.name=netsentience

spring.datasource.url=jdbc:postgresql://localhost:5433/netsentience
spring.datasource.username=myuser
spring.datasource.password=secretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update