spring.application.name=netsentience

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/netsentience
spring.datasource.username=myuser
spring.datasource.password=secretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
# This automatically creates tables based on your Java code (Great for dev, bad for prod)
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in the console so we can see what's happening
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true